from __future__ import annotations

from importlib import resources


def test_postgres_schema_uses_postgresql_contract() -> None:
    schema = resources.files("deepagents.rag").joinpath("schemas", "postgres_schema.sql").read_text(encoding="utf-8")

    assert "PostgreSQL" in schema
    assert "TIMESTAMPTZ" in schema
    assert "JSONB" in schema
    assert "GENERATED BY DEFAULT AS IDENTITY" in schema
    assert "CREATE OR REPLACE FUNCTION rag_touch_updated_at" in schema
    assert "CREATE TABLE IF NOT EXISTS rag_eval_runs" in schema
    assert "CREATE TABLE IF NOT EXISTS rag_eval_results" in schema
    assert "ALTER TABLE IF EXISTS rag_knowledge_bases" in schema
    assert "ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb" in schema
    assert "dataset_name VARCHAR(128) NOT NULL" in schema
    assert "recall_at_2 NUMERIC(8,6) NOT NULL DEFAULT 0.0" in schema
    assert "ndcg_at_5 NUMERIC(8,6) NOT NULL DEFAULT 0.0" in schema
    assert "ENGINE=InnoDB" not in schema
    assert "AUTO_INCREMENT" not in schema
