from __future__ import annotations

from importlib import resources


def test_postgres_schema_uses_postgresql_contract() -> None:
    schema = resources.files("deepagents.rag").joinpath("schemas", "postgres_schema.sql").read_text(encoding="utf-8")

    assert "PostgreSQL" in schema
    assert "TIMESTAMPTZ" in schema
    assert "JSONB" in schema
    assert "GENERATED BY DEFAULT AS IDENTITY" in schema
    assert "CREATE OR REPLACE FUNCTION rag_touch_updated_at" in schema
    assert "ENGINE=InnoDB" not in schema
    assert "AUTO_INCREMENT" not in schema
