from __future__ import annotations

from importlib import resources


def test_memory_postgres_schema_contains_expected_tables() -> None:
    schema = resources.files("deepagents.memory").joinpath("schemas", "postgres_schema.sql").read_text(encoding="utf-8")

    assert "agent_memory_items" in schema
    assert "agent_memory_events" in schema
    assert "agent_session_summaries" in schema
    assert "JSONB" in schema
    assert "GENERATED BY DEFAULT AS IDENTITY" in schema
    assert "ENGINE=InnoDB" not in schema
